services:
  # Main web service
  - type: web
    name: docgen-web
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production

  # Python API service
  - type: web
    name: docgen-api
    env: python
    buildCommand: pip install -r server/requirements.txt
    startCommand: cd server && gunicorn server:app
    envVars:
      - key: RENDER
        value: true
