services:
  # Python API Backend - This handles document processing only
  - type: web
    name: docexp-api
    env: python
    runtime: python3.9
    buildCommand: pip install -r server/requirements.txt
    startCommand: cd server && gunicorn --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHONPATH
        value: ./server
      - key: DEBUG
        value: "false"
      - key: FRONTEND_URL
        value: https://docexp.onreader.com
      - key: API_URL
        value: https://docexp-api.onrender.com
    healthCheckPath: /status
    autoDeploy: true
    domains:
      - docexp-api.onrender.com

  # Main Frontend - This is where users will access the application
  - type: web
    name: docexp
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://docexp.onreader.com
      - key: PYTHON_SERVICE_URL
        value: https://docexp-api.onrender.com
    healthCheckPath: /health
    autoDeploy: true
    domains:
      - docexp.onreader.com
