services:
  # Frontend Node.js
  - type: web
    name: docgen-web
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_SERVICE_URL
        fromService:
          name: docgen-api
          type: web
          property: url
    healthCheckPath: /health
    autoDeploy: true

  # Backend Python (FastAPI/Flask)
  - type: web
    name: docgen-api
    env: python
    runtime: python3.9
    buildCommand: pip install -r server/requirements.txt
    startCommand: cd server && gunicorn --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHONPATH
        value: ./server
      - key: DEBUG
        value: "false"
    healthCheckPath: /status
    autoDeploy: true
