services:
  # Main web service - Run Node.js app that serves the frontend
  - type: web
    name: docgen-web
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_SERVICE_URL
        fromService:
          name: docgen-api
          type: web
          property: url

  # Python API service - Handle document generation
  - type: web
    name: docgen-api
    env: python
    buildCommand: pip install -r server/requirements.txt
    startCommand: cd server && gunicorn --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHONPATH
        value: ./server
      - key: DEBUG
        value: "false"
